version: '3.3'
services:
  next-app:
    container_name: vardast-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - myNet
networks:
  myNet:
    external: true
