/* eslint-disable no-unused-vars */
enum QUERY_FUNCTIONS_KEY {
  GET_ALL_BRANDS_COUNT_QUERY_KEY = "GET_ALL_BRANDS_COUNT_QUERY_KEY",
  GET_ALL_BRANDS_QUERY_KEY = "GET_ALL_BRANDS_QUERY_KEY",
  ALL_BRANDS_QUERY_KEY = "ALL_BRANDS_QUERY_KEY",
  ALL_CATEGORIES_QUERY_KEY = "ALL_CATEGORIES_QUERY_KEY",
  ALL_PRODUCTS_QUERY_KEY = "ALL_PRODUCTS_QUERY_KEY",
  ALL_SELLERS_COUNT_QUERY_KEY = "ALL_SELLERS_COUNT_QUERY_KEY",
  ALL_SELLERS_QUERY_KEY = "ALL_SELLERS_QUERY_KEY",
  ALL_BRAND_QUERY_KEY = "ALL_BRAND_QUERY_KEY",
  ALL_CATEGORY_BASICS_QUERY_KEY = "ALL_CATEGORY_BASICS_QUERY_KEY",
  CATEGORY_QUERY_KEY = "CATEGORY_QUERY_KEY",
  PRODUCT_BASICS_QUERY_KEY = "PRODUCT_BASICS_QUERY_KEY",
  PRODUCT_QUERY_KEY = "PRODUCT_QUERY_KEY",
  SELLER_QUERY_KEY = "SELLER_QUERY_KEY",
  BRAND_QUERY_KEY = "BRAND_QUERY_KEY",
  VOCABULARY_QUERY_KEY = "VOCABULARY_QUERY_KEY"
}

export default QUERY_FUNCTIONS_KEY
